import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import FrontPageCard from "../components/FrontPageCard"

const Home: NextPage = () => {
  return (
    <div className="p-2">
      <Head>
        <title>Send app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-1 p-4 justify-center items-center">
        <h1 className="headline">
          Send App
        </h1>

        <p className="m-3 text-center text-xl">
          Add your ascends or view statistics
        </p>

        <div className="flex justify-center">
        <FrontPageCard headline="Add ascent" desc="Update with your latest ascends" link="/add"></FrontPageCard>
        <FrontPageCard headline="Statistics" desc="View all your statistics" link="/statistics"></FrontPageCard>
        </div>
      </main>

    </div>
  )
}

export default Home
